import { useState, useMemo, useEffect, useRef, useCallback } from 'react';
import {
  Users, Share2, CalendarDays, Mail, Megaphone, Search,
  BarChart3, Swords, FileText, Copy, Check, Lock,
  RefreshCw, ChevronLeft, ChevronRight, Zap, X,
  TrendingUp, MoreHorizontal, AlertCircle, Download, Loader2,
} from 'lucide-react';

const BMAC_URL          = 'https://buymeacoffee.com/marketgenie';
const BMAC_DISMISSED_KEY = 'mg_coffee_dismissed';

// ── PDF helpers ────────────────────────────────────────────────────────────

function stripMd(text) {
  return text
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\*([^*]+)\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .trim();
}

function pdfSlugify(text) {
  return (text || '')
    .slice(0, 40)
    .replace(/[^a-zA-Z0-9 -]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'Strategy';
}

function pdfDateStr() {
  return new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

function pdfDateSlug() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

async function exportToPDF(sections, businessDescription) {
  const { jsPDF } = await import('jspdf');

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const PW = doc.internal.pageSize.getWidth();   // 210
  const PH = doc.internal.pageSize.getHeight();  // 297
  const M  = 20;      // margin
  const CW = PW - 2 * M; // 170
  const LH = 5;       // base line height mm

  const EM  = [5, 150, 105];     // emerald #059669
  const EM2 = [4, 120, 87];      // #047857
  const S9  = [15, 23, 42];      // slate-900
  const S7  = [51, 65, 85];      // slate-700
  const S5  = [100, 116, 139];   // slate-500
  const S2  = [203, 213, 225];   // slate-300

  // ── Helper: check page overflow and add continuation if needed ──────────
  function checkPage(doc, y, needed, sectionTitle) {
    if (y + needed < PH - 15) return y;
    doc.addPage();
    doc.setFillColor(...EM);
    doc.rect(0, 0, PW, 3, 'F');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...S9);
    doc.text(sectionTitle, M, 13);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...S5);
    doc.text(' (continued)', M + doc.getTextWidth(sectionTitle), 13);
    return 22;
  }

  // ── Cover page ──────────────────────────────────────────────────────────
  doc.setFillColor(...EM);
  doc.rect(0, 0, PW, 72, 'F');
  doc.setFillColor(...EM2);
  doc.rect(0, 0, PW, 10, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(255, 255, 255);
  doc.text('MarketGenie', M, 42);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(167, 243, 208);
  doc.text('Marketing Strategy Report', M, 56);

  doc.setFontSize(9);
  doc.text('Powered by Claude AI', PW - M, 18, { align: 'right' });

  // Prepared for section
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...S5);
  doc.text('PREPARED FOR', M, 96);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(17);
  doc.setTextColor(...S9);
  const bizLines = doc.splitTextToSize(businessDescription, CW);
  doc.text(bizLines, M, 107);

  const afterBiz = 107 + bizLines.length * 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...S5);
  doc.text(`Generated: ${pdfDateStr()}`, M, afterBiz + 10);
  doc.text(`${sections.length} section${sections.length !== 1 ? 's' : ''} included`, M, afterBiz + 18);

  doc.setDrawColor(...S2);
  doc.setLineWidth(0.4);
  doc.line(M, afterBiz + 26, PW - M, afterBiz + 26);

  doc.setFontSize(9);
  doc.setTextColor(...S5);
  doc.text('Generated by MarketGenie — AI-powered marketing for every business.', M, afterBiz + 34);
  doc.text('marketgenie.app', M, afterBiz + 41);

  doc.setFontSize(8);
  doc.setTextColor(...S2);
  doc.text('1', PW / 2, PH - 8, { align: 'center' });

  // ── Section pages ────────────────────────────────────────────────────────
  for (let si = 0; si < sections.length; si++) {
    const sec = sections[si];
    doc.addPage();

    // Emerald bar
    doc.setFillColor(...EM);
    doc.rect(0, 0, PW, 3, 'F');

    // Section counter
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...EM);
    doc.text(`Section ${si + 1} of ${sections.length}`, M, 13);

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(...S9);
    const titleLines = doc.splitTextToSize(sec.title, CW);
    doc.text(titleLines, M, 24);
    const afterTitle = 24 + titleLines.length * 8;

    // Accent + rule
    doc.setDrawColor(...EM);
    doc.setLineWidth(0.9);
    doc.line(M, afterTitle + 4, M + 28, afterTitle + 4);
    doc.setDrawColor(...S2);
    doc.setLineWidth(0.3);
    doc.line(M + 29, afterTitle + 4, PW - M, afterTitle + 4);

    let y = afterTitle + 13;

    // Content
    const content = sec.content || '(No content available for this section.)';
    for (const line of content.split('\n')) {
      const t = line.trim();

      if (!t) { y += LH * 0.45; continue; }

      if (t.startsWith('### ')) {
        y = checkPage(doc, y, LH + 3, sec.title);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(11);
        doc.setTextColor(...EM);
        const split = doc.splitTextToSize(stripMd(t.slice(4)), CW);
        doc.text(split, M, y);
        y += split.length * LH + 2;

      } else if (t.startsWith('## ')) {
        y = checkPage(doc, y, LH + 4, sec.title);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(12);
        doc.setTextColor(...EM);
        const split = doc.splitTextToSize(stripMd(t.slice(3)), CW);
        doc.text(split, M, y);
        y += split.length * LH + 3;

      } else if (/^[-•*]\s/.test(t)) {
        const split = doc.splitTextToSize('• ' + stripMd(t.slice(2)), CW - 6);
        y = checkPage(doc, y, split.length * LH, sec.title);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(...S7);
        doc.text(split, M + 5, y);
        y += split.length * LH + 1;

      } else if (/^\d+\.\s/.test(t)) {
        const split = doc.splitTextToSize(stripMd(t), CW - 6);
        y = checkPage(doc, y, split.length * LH, sec.title);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(...S7);
        doc.text(split, M + 5, y);
        y += split.length * LH + 1;

      } else {
        const split = doc.splitTextToSize(stripMd(t), CW);
        y = checkPage(doc, y, split.length * LH, sec.title);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(...S7);
        doc.text(split, M, y);
        y += split.length * LH + 1.5;
      }
    }

    // Page number
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...S2);
    doc.text(String(si + 2), PW / 2, PH - 8, { align: 'center' });
  }

  doc.save(`MarketGenie-Strategy-${pdfSlugify(businessDescription)}-${pdfDateSlug()}.pdf`);
}

// ── Section metadata (Lucide icons) ───────────────────────────────────────

const SECTION_META = [
  { key: 'target',     match: 'target audience', Icon: Users,        short: 'Audience', color: '#ef4444' },
  { key: 'social',     match: 'social media',    Icon: Share2,       short: 'Social',   color: '#8b5cf6' },
  { key: 'calendar',   match: '30-day',          Icon: CalendarDays, short: 'Calendar', color: '#3b82f6' },
  { key: 'email',      match: 'email',           Icon: Mail,         short: 'Email',    color: '#06b6d4' },
  { key: 'ads',        match: 'ad copy',         Icon: Megaphone,    short: 'Ads',      color: '#059669' },
  { key: 'seo',        match: 'seo',             Icon: Search,       short: 'SEO',      color: '#d97706' },
  { key: 'score',      match: 'marketing score', Icon: BarChart3,    short: 'Score',    color: '#059669' },
  { key: 'competitor', match: 'competitor',      Icon: Swords,       short: 'Compete',  color: '#f97316' },
];

function getMeta(title) {
  if (!title) return { key: 'other', Icon: FileText, short: '...', color: '#64748b' };
  const lower = title.toLowerCase();
  return SECTION_META.find(m => lower.includes(m.match)) ||
    { key: 'other', Icon: FileText, short: title.slice(0, 10), color: '#64748b' };
}

const FULLY_LOCKED = new Set(['ads', 'seo', 'competitor']);

// ── Parsers ────────────────────────────────────────────────────────────────

function parseSections(text) {
  const parts = text.split(/^## /m).slice(1);
  return parts
    .map(part => {
      const trimmed = part.trim();
      if (!trimmed) return null;
      const nl = trimmed.indexOf('\n');
      return nl === -1
        ? { title: trimmed, content: '' }
        : { title: trimmed.slice(0, nl).trim(), content: trimmed.slice(nl + 1).trim() };
    })
    .filter(Boolean);
}

function extractScore(content) {
  const m = content.match(/overall\s+score[:\s]*(\d{1,3})\s*(?:\/\s*100)?/i)
         || content.match(/(\d{1,3})\s*\/\s*100/);
  if (m) {
    const n = parseInt(m[1], 10);
    if (n >= 0 && n <= 100) return n;
  }
  return 72;
}

function parseBreakdown(content) {
  const scores = [];
  for (const line of content.split('\n')) {
    const t = line.trim().replace(/\*\*/g, '');
    const m = t.match(/^[-•*]?\s*([^:]+):\s*(\d{1,3})\s*\/\s*100/);
    if (m) {
      const label = m[1].trim();
      const value = parseInt(m[2], 10);
      if (!label.toLowerCase().includes('overall') && value >= 0 && value <= 100)
        scores.push({ label, value });
    }
  }
  return scores;
}

function parseQuickWins(content) {
  const wins = [];
  let inWins = false;
  for (const line of content.split('\n')) {
    const t = line.trim();
    if (/quick\s+win/i.test(t)) { inWins = true; continue; }
    if (inWins && /^\d+\.\s+/.test(t))
      wins.push(t.replace(/^\d+\.\s+/, '').replace(/\*\*/g, '').trim());
    if (inWins && t.startsWith('##')) break;
  }
  return wins;
}

function parseEmailTemplates(content) {
  const templates = [];
  const parts = content.split(/\n(?=\d+\.\s)/);
  for (const part of parts) {
    const trimmed = part.trim();
    if (!trimmed) continue;
    const titleMatch = trimmed.match(/^\d+\.\s+(.+)/);
    const title = titleMatch ? titleMatch[1].trim() : 'Email Template';
    const subjectMatch = trimmed.match(/subject[:\s]+(.+)/i);
    const bodyMatch    = trimmed.match(/body[:\s]+([\s\S]+)/i);
    const subject = subjectMatch ? subjectMatch[1].replace(/\*\*/g, '').trim() : '';
    const body    = bodyMatch    ? bodyMatch[1].replace(/\*\*/g, '').trim()    : '';
    if (subject || body) templates.push({ title, subject, body });
  }
  return templates;
}

function splitKeywords(text) {
  return text
    .replace(/\*\*/g, '').replace(/[()]/g, '')
    .split(/[,;|]/)
    .map(k => k.trim().replace(/^[-•\d.]\s*/, '').replace(/^\d+-\d+\s*/, ''))
    .filter(k => k.length > 2 && !/^(list|keyword|phrase|include|cover)/i.test(k));
}

function parseSEOKeywords(content) {
  const result = { primary: [], secondary: [], longTail: [] };
  let currentGroup = null;
  for (const line of content.split('\n')) {
    const t = line.trim();
    if (!t) continue;
    const lower = t.toLowerCase();
    if (/primary/i.test(lower) && !result.primary.length) {
      currentGroup = 'primary';
      result.primary.push(...splitKeywords(t.includes(':') ? t.slice(t.indexOf(':') + 1) : ''));
    } else if (/secondary/i.test(lower) && !result.secondary.length) {
      currentGroup = 'secondary';
      result.secondary.push(...splitKeywords(t.includes(':') ? t.slice(t.indexOf(':') + 1) : ''));
    } else if (/long.?tail/i.test(lower) && !result.longTail.length) {
      currentGroup = 'longTail';
      result.longTail.push(...splitKeywords(t.includes(':') ? t.slice(t.indexOf(':') + 1) : ''));
    } else if (currentGroup && (t.startsWith('-') || t.startsWith('•') || t.startsWith('*') || /^\d+\./.test(t))) {
      const kw = t.replace(/^[-•*\d.]\s*/, '').replace(/\*\*/g, '').trim();
      if (kw) result[currentGroup].push(kw);
    }
  }
  return result;
}

function parseAdCopy(content) {
  const lines = content.split('\n');
  let section = null, subsection = null;
  const googleHeadlines = [], googleDescriptions = [];
  let fbHeadline = '', fbBody = '', fbCTA = '';

  for (const line of lines) {
    const t = line.trim();
    if (!t) continue;
    const lower = t.toLowerCase().replace(/\*/g, '');
    if (/google/i.test(lower))            { section = 'google';   subsection = null; continue; }
    if (/facebook|instagram/i.test(lower)) { section = 'facebook'; subsection = null; continue; }

    if (section === 'google') {
      if (/headline/i.test(lower))      subsection = 'headlines';
      else if (/desc/i.test(lower))     subsection = 'descriptions';
      if (t.startsWith('-') || t.startsWith('"') || /^\d+\./.test(t)) {
        const text = t.replace(/^[-"'\d.•*]\s*"?/, '').replace(/"$/, '').replace(/\*\*/g, '').trim();
        if (text && text.length > 3) {
          if (subsection === 'headlines'     && googleHeadlines.length    < 5) googleHeadlines.push(text);
          else if (subsection === 'descriptions' && googleDescriptions.length < 3) googleDescriptions.push(text);
        }
      }
    } else if (section === 'facebook') {
      const hMatch = t.match(/\*{0,2}headline[:\*\s]+(.+)/i);
      const bMatch = t.match(/\*{0,2}body[:\*\s]+(.+)/i);
      const cMatch = t.match(/\*{0,2}cta[^:]*[:\*\s]+(.+)/i);
      if (hMatch && !fbHeadline) fbHeadline = hMatch[1].replace(/\*\*/g, '').trim();
      else if (bMatch && !fbBody) fbBody = bMatch[1].replace(/\*\*/g, '').trim();
      else if (cMatch && !fbCTA)  fbCTA  = cMatch[1].replace(/\*\*/g, '').trim();
    }
  }
  return { googleHeadlines, googleDescriptions, fbHeadline, fbBody, fbCTA };
}

// ── Platform Icons ─────────────────────────────────────────────────────────

function InstagramIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" style={{ flexShrink: 0 }}>
      <defs>
        <radialGradient id="ig-grad" cx="30%" cy="110%" r="150%">
          <stop offset="0%"   stopColor="#fdf497" />
          <stop offset="10%"  stopColor="#fd5949" />
          <stop offset="50%"  stopColor="#d6249f" />
          <stop offset="100%" stopColor="#285AEB" />
        </radialGradient>
      </defs>
      <rect x="1" y="1" width="22" height="22" rx="6" fill="url(#ig-grad)" />
      <circle cx="12" cy="12" r="5" stroke="white" strokeWidth="2" fill="none" />
      <circle cx="17.8" cy="6.2" r="1.4" fill="white" />
    </svg>
  );
}

function FacebookIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" style={{ flexShrink: 0 }}>
      <rect x="1" y="1" width="22" height="22" rx="5" fill="#1877f2" />
      <path d="M16 8h-2a1 1 0 0 0-1 1v2h3l-.5 3H13v7h-3v-7H8v-3h2V9a4 4 0 0 1 4-4h2v3z" fill="white" />
    </svg>
  );
}

function TikTokIcon() {
  return (
    <svg width="20" height="20" viewBox="0 0 24 24" style={{ flexShrink: 0 }}>
      <rect x="1" y="1" width="22" height="22" rx="5" fill="#010101" />
      <path d="M17 7.5A3.5 3.5 0 0 1 13.5 4h-2.5v10.5a1.5 1.5 0 1 1-1.5-1.5v-2.5A4 4 0 1 0 14 14.5V9a5.6 5.6 0 0 0 3 .88V7.5z" fill="white" />
      <path d="M15.5 7.5A3.5 3.5 0 0 1 12 4h-1a4.5 4.5 0 0 0 4.5 4.5z" fill="#69C9D0" opacity="0.8" />
    </svg>
  );
}

const PLATFORM_ICONS = {
  instagram: <InstagramIcon />,
  facebook:  <FacebookIcon />,
  tiktok:    <TikTokIcon />,
};

// ── Markdown renderers ─────────────────────────────────────────────────────

function InlineText({ text }) {
  const parts = text.split(/\*\*(.*?)\*\*/);
  return (
    <>
      {parts.map((p, i) =>
        i % 2 === 1
          ? <strong key={i} className="text-slate-800 font-bold">{p}</strong>
          : p
      )}
    </>
  );
}

function MarkdownTable({ rows }) {
  const dataRows = rows.filter(r => !/^\|[-:\s|]+\|$/.test(r));
  if (dataRows.length < 2) return null;
  const parse = row => row.split('|').slice(1, -1).map(c => c.trim());
  const [header, ...body] = dataRows;
  const headers = parse(header);
  return (
    <div className="overflow-x-auto my-4 rounded-xl" style={{ border: '1px solid #e2e8f0' }}>
      <table className="w-full text-sm border-collapse">
        <thead>
          <tr style={{ background: '#ECFDF5' }}>
            {headers.map((h, i) => (
              <th key={i} className="px-4 py-3 text-left font-bold text-emerald-800 border-b border-emerald-100 text-xs uppercase tracking-wider">{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {body.map((row, ri) => (
            <tr key={ri} style={{ background: ri % 2 === 0 ? '#fff' : '#f8fafc' }}>
              {parse(row).map((cell, ci) => (
                <td key={ci} className="px-4 py-2.5 text-slate-600 border-b border-slate-50 text-sm">{cell}</td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function Line({ line }) {
  const t = line.trim();
  if (!t) return <div className="h-2" />;
  if (/^-{3,}$/.test(t) || /^_{3,}$/.test(t) || /^\*{3,}$/.test(t))
    return <hr className="border-slate-200 my-4" />;
  if (t.startsWith('### '))
    return <h4 className="text-slate-900 font-bold text-sm mt-5 mb-2">{t.slice(4)}</h4>;

  const platformMatch = t.match(/^\*\*(Instagram|Facebook|TikTok)[^*]*\*\*[:\s]*(.*)/i);
  if (platformMatch) {
    const platform = platformMatch[1].toLowerCase();
    const rest     = platformMatch[2].trim();
    return (
      <div className="flex items-start gap-2.5 mt-5 mb-2">
        <span className="mt-0.5">{PLATFORM_ICONS[platform]}</span>
        <div>
          <span className="font-black text-slate-900 text-sm">{platformMatch[1]}</span>
          {rest && <span className="text-slate-600 text-sm ml-1">{rest}</span>}
        </div>
      </div>
    );
  }

  const bullet = t.match(/^[-•*]\s+(.*)/);
  if (bullet) return (
    <div className="flex items-start gap-3 mb-2">
      <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 flex-shrink-0 mt-[7px]" />
      <span className="text-slate-600 text-sm leading-relaxed"><InlineText text={bullet[1]} /></span>
    </div>
  );

  const numbered = t.match(/^(\d+)\.\s+(.*)/);
  if (numbered) return (
    <div className="flex items-start gap-3 mb-2.5">
      <span className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-700 text-xs font-black flex-shrink-0 flex items-center justify-center mt-0.5">{numbered[1]}</span>
      <span className="text-slate-600 text-sm leading-relaxed"><InlineText text={numbered[2]} /></span>
    </div>
  );

  if (t.startsWith('**') && t.endsWith('**') && !t.slice(2, -2).includes('**'))
    return <p className="text-slate-800 font-bold mt-4 mb-1.5 text-sm">{t.slice(2, -2)}</p>;

  return (
    <p className="text-slate-600 text-sm leading-relaxed mb-2">
      <InlineText text={t} />
    </p>
  );
}

function renderContent(content) {
  const lines = content.split('\n');
  const elements = [];
  let i = 0, key = 0;
  while (i < lines.length) {
    if (lines[i].trim().startsWith('|')) {
      const tableRows = [];
      while (i < lines.length && lines[i].trim().startsWith('|')) {
        tableRows.push(lines[i].trim());
        i++;
      }
      elements.push(<MarkdownTable key={key++} rows={tableRows} />);
      continue;
    }
    elements.push(<Line key={key++} line={lines[i]} />);
    i++;
  }
  return elements;
}

// ── Mini Score Ring (sidebar) ──────────────────────────────────────────────

function MiniScoreRing({ score }) {
  const r = 18;
  const C = 2 * Math.PI * r;
  const offset = C * (1 - score / 100);
  const color = score >= 80 ? '#10b981' : score >= 60 ? '#f59e0b' : '#ef4444';
  return (
    <svg width="48" height="48" viewBox="0 0 48 48" className="flex-shrink-0">
      <circle cx="24" cy="24" r={r} fill="none" stroke="#e2e8f0" strokeWidth="5" />
      <circle cx="24" cy="24" r={r} fill="none" stroke={color} strokeWidth="5"
        strokeLinecap="round"
        strokeDasharray={C}
        strokeDashoffset={offset}
        transform="rotate(-90 24 24)"
        style={{ transition: 'stroke-dashoffset 0.5s ease, stroke 0.3s ease' }}
      />
    </svg>
  );
}

// ── Score Ring (content area) ──────────────────────────────────────────────

function ScoreRing({ score }) {
  const [count, setCount] = useState(0);
  const C = 2 * Math.PI * 40;

  useEffect(() => {
    let frame, start = null;
    const duration = 1800;
    const animate = ts => {
      if (!start) start = ts;
      const p = Math.min((ts - start) / duration, 1);
      setCount(Math.round((1 - Math.pow(1 - p, 3)) * score));
      if (p < 1) frame = requestAnimationFrame(animate);
    };
    frame = requestAnimationFrame(animate);
    return () => cancelAnimationFrame(frame);
  }, [score]);

  const offset = C * (1 - count / 100);
  const color  = count >= 80 ? '#10B981' : count >= 60 ? '#f59e0b' : '#ef4444';
  const label  = count >= 80 ? 'Excellent' : count >= 60 ? 'Good' : 'Needs Work';

  return (
    <div className="flex flex-col items-center">
      <div className="relative w-36 h-36">
        <svg viewBox="0 0 100 100" className="w-full h-full -rotate-90">
          <circle cx="50" cy="50" r="40" fill="none" stroke="#e2e8f0" strokeWidth="8" />
          <circle cx="50" cy="50" r="40" fill="none" stroke={color} strokeWidth="8"
            strokeLinecap="round" strokeDasharray={C} strokeDashoffset={offset}
            style={{ transition: 'stroke-dashoffset 0.04s linear' }} />
        </svg>
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <span className="text-4xl font-black text-slate-900">{count}</span>
          <span className="text-slate-400 text-xs font-semibold">/100</span>
        </div>
      </div>
      <span className="mt-2.5 text-xs font-bold px-3.5 py-1.5 rounded-full"
        style={{ background: color + '18', color }}>
        {label}
      </span>
    </div>
  );
}

// ── Breakdown Bar ──────────────────────────────────────────────────────────

function BreakdownBar({ label, value, delay = 0 }) {
  const [width, setWidth] = useState(0);
  useEffect(() => {
    const t = setTimeout(() => setWidth(value), 200 + delay);
    return () => clearTimeout(t);
  }, [value, delay]);
  const color = value >= 80 ? '#10B981' : value >= 60 ? '#f59e0b' : '#ef4444';
  return (
    <div className="mb-3.5">
      <div className="flex justify-between items-center mb-1">
        <span className="text-sm font-medium text-slate-700">{label}</span>
        <span className="text-sm font-black" style={{ color }}>{value}<span className="text-slate-400 font-normal text-xs">/100</span></span>
      </div>
      <div className="h-2 rounded-full bg-slate-100 overflow-hidden">
        <div className="h-full rounded-full transition-all duration-1000 ease-out"
          style={{ width: `${width}%`, background: color }} />
      </div>
    </div>
  );
}

// ── Quick Wins Checklist ───────────────────────────────────────────────────

function QuickWinsChecklist({ wins, onCheckedChange }) {
  const [checked, setChecked] = useState(new Set());

  // Notify parent on mount with total
  useEffect(() => {
    onCheckedChange?.(0, wins.length);
  }, [wins.length]); // eslint-disable-line react-hooks/exhaustive-deps

  const toggle = i => {
    const next = new Set(checked);
    next.has(i) ? next.delete(i) : next.add(i);
    setChecked(next);
    onCheckedChange?.(next.size, wins.length);
  };

  const done = checked.size;

  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <h4 className="font-black text-slate-900 text-sm flex items-center gap-2">
          <div className="w-6 h-6 rounded-lg bg-emerald-100 flex items-center justify-center">
            <Zap className="w-3.5 h-3.5 text-emerald-600" />
          </div>
          Quick Wins — This Week
        </h4>
        <span className="text-xs font-bold px-2.5 py-1 rounded-full transition-all"
          style={{
            background: done === wins.length && wins.length > 0 ? '#ECFDF5' : '#f1f5f9',
            color: done === wins.length && wins.length > 0 ? '#065F46' : '#64748b',
          }}>
          {done}/{wins.length} done
        </span>
      </div>
      <div className="space-y-2">
        {wins.map((win, i) => (
          <button key={i} onClick={() => toggle(i)}
            className="w-full flex items-start gap-3 p-3 rounded-xl text-left transition-all group"
            style={{
              background: checked.has(i) ? '#f0fdf4' : '#f8fafc',
              border: `1px solid ${checked.has(i) ? '#a7f3d0' : '#e2e8f0'}`,
            }}>
            {/* Checkbox */}
            <div className="flex-shrink-0 w-5 h-5 rounded-md border-2 flex items-center justify-center mt-0.5 transition-all"
              style={{
                background:   checked.has(i) ? '#10B981' : 'transparent',
                borderColor:  checked.has(i) ? '#10B981' : '#cbd5e1',
              }}>
              {checked.has(i) && <Check className="w-3 h-3 text-white" strokeWidth={3} />}
            </div>
            <span className="text-sm leading-relaxed transition-all"
              style={{ color: checked.has(i) ? '#94a3b8' : '#374151', textDecoration: checked.has(i) ? 'line-through' : 'none' }}>
              {win}
            </span>
          </button>
        ))}
      </div>
    </div>
  );
}

// ── Pro Gate ───────────────────────────────────────────────────────────────

function ProGate({ children, feature = 'this section', onShowWaitlist }) {
  return (
    <div style={{ position: 'relative', borderRadius: 14, overflow: 'hidden', minHeight: 260 }}>
      <div style={{ filter: 'blur(6px)', pointerEvents: 'none', userSelect: 'none', opacity: 0.45, transform: 'scale(1.02)', transformOrigin: 'center' }}>
        {children}
      </div>
      <div style={{ position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(248,250,252,0.85)', backdropFilter: 'blur(3px)' }}>
        <div style={{ textAlign: 'center', maxWidth: 320, padding: '28px 24px', background: '#ffffff', borderRadius: 18, border: '1px solid #e2e8f0', boxShadow: '0 12px 40px rgba(0,0,0,0.09)', margin: '0 16px' }}>
          <div style={{ width: 52, height: 52, borderRadius: 14, margin: '0 auto 14px', background: '#f0fdf4', border: '1px solid #bbf7d0', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Lock style={{ width: 22, height: 22, color: '#10b981' }} />
          </div>
          <h3 style={{ margin: '0 0 6px', fontWeight: 900, fontSize: 17, color: '#0f172a' }}>Unlock with Pro Plan</h3>
          <p style={{ margin: '0 0 18px', color: '#64748b', fontSize: 13, lineHeight: 1.6 }}>
            Upgrade to Pro to unlock <strong style={{ color: '#0f172a' }}>{feature}</strong> and all premium sections.
          </p>
          <button
            onClick={onShowWaitlist}
            style={{ display: 'block', width: '100%', padding: '11px 0', background: 'linear-gradient(135deg,#059669,#047857)', color: '#fff', borderRadius: 10, fontWeight: 700, fontSize: 13, textAlign: 'center', boxShadow: '0 4px 14px rgba(5,150,105,0.28)', border: 'none', cursor: 'pointer', transition: 'transform 0.15s ease' }}
            onMouseEnter={e => (e.currentTarget.style.transform = 'scale(1.02)')}
            onMouseLeave={e => (e.currentTarget.style.transform = 'scale(1)')}>
            Join Waitlist
          </button>
          <p style={{ marginTop: 10, color: '#94a3b8', fontSize: 11, lineHeight: 1.5 }}>
            Free includes: Target Audience · Social · Calendar · 1 Email Template
          </p>
        </div>
      </div>
    </div>
  );
}

// ── Score Section ──────────────────────────────────────────────────────────

function ScoreSection({ content, isPro, onShowWaitlist, adjustedScore, onCheckedChange }) {
  const baseScore  = extractScore(content);
  const breakdown  = parseBreakdown(content);
  const quickWins  = parseQuickWins(content);
  const expMatch   = content.match(/explanation[:\s]+([\s\S]*?)(?=quick wins|\n\n\n|$)/i);
  const explanation = expMatch ? expMatch[1].replace(/\*\*/g, '').trim().split('\n')[0] : '';

  return (
    <div className="space-y-5">
      {/* Ring — always visible */}
      <div className="result-card p-7 text-center">
        <p className="text-xs font-bold tracking-widest uppercase text-slate-400 mb-5">Overall Marketing Score</p>
        <ScoreRing score={adjustedScore ?? baseScore} />
        {explanation && (
          <p className="text-slate-500 text-sm mt-4 max-w-lg mx-auto leading-relaxed">{explanation}</p>
        )}
        {!isPro && (
          <div className="mt-4 inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-semibold"
            style={{ background: '#FEF3C7', color: '#92400e', border: '1px solid #FDE68A' }}>
            <Lock className="w-3 h-3" />
            Full breakdown &amp; Quick Wins unlocked with Pro
          </div>
        )}
      </div>

      {/* Breakdown + Quick Wins */}
      {isPro ? (
        <>
          {breakdown.length > 0 && (
            <div className="result-card p-6">
              <h4 className="font-black text-slate-900 mb-4 text-sm flex items-center gap-2">
                <div className="w-6 h-6 rounded-lg bg-emerald-100 flex items-center justify-center">
                  <BarChart3 className="w-3.5 h-3.5 text-emerald-600" />
                </div>
                Score Breakdown
              </h4>
              {breakdown.map((item, i) => (
                <BreakdownBar key={i} label={item.label} value={item.value} delay={i * 80} />
              ))}
            </div>
          )}
          {quickWins.length > 0 && (
            <div className="result-card p-6">
              <QuickWinsChecklist wins={quickWins} onCheckedChange={onCheckedChange} />
            </div>
          )}
        </>
      ) : (
        <ProGate feature="Score Breakdown & Quick Wins" onShowWaitlist={onShowWaitlist}>
          <div className="space-y-4">
            {breakdown.length > 0 && (
              <div className="result-card p-6">
                <h4 className="font-black text-slate-900 mb-4 text-sm">Score Breakdown</h4>
                {breakdown.map((item, i) => <BreakdownBar key={i} label={item.label} value={item.value} delay={0} />)}
              </div>
            )}
            {quickWins.length > 0 && (
              <div className="result-card p-6">
                <QuickWinsChecklist wins={quickWins} onCheckedChange={() => {}} />
              </div>
            )}
          </div>
        </ProGate>
      )}
    </div>
  );
}

// ── Email Section ──────────────────────────────────────────────────────────

function EmailSection({ content, isPro, onShowWaitlist }) {
  const templates      = parseEmailTemplates(content);
  const [copied, setCopied] = useState(null);

  const copyTemplate = (i) => {
    const t = templates[i];
    navigator.clipboard.writeText(`Subject: ${t.subject}\n\n${t.body}`).catch(() => {});
    setCopied(i);
    setTimeout(() => setCopied(null), 2000);
  };

  if (!templates.length)
    return <div className="result-card p-6 sm:p-8">{renderContent(content)}</div>;

  const first = templates[0];
  const rest  = templates.slice(1);

  return (
    <div className="space-y-4">
      <div className="result-card p-6">
        <div className="flex items-start justify-between mb-4 gap-3">
          <div>
            <p className="text-xs font-bold uppercase tracking-widest mb-1" style={{ color: '#059669' }}>Template 1 of {templates.length}</p>
            <h4 className="font-black text-slate-900 text-sm">{first.title}</h4>
          </div>
          <CopyBtn text={`Subject: ${first.subject}\n\n${first.body}`} />
        </div>
        {first.subject && (
          <div className="mb-3 p-3 rounded-xl" style={{ background: '#f0fdf4', border: '1px solid #d1fae5' }}>
            <p className="text-xs font-bold uppercase tracking-wider mb-0.5" style={{ color: '#059669' }}>Subject</p>
            <p className="text-sm font-semibold text-slate-800">{first.subject}</p>
          </div>
        )}
        {first.body && (
          <div className="p-3 rounded-xl" style={{ background: '#f8fafc', border: '1px solid #e2e8f0' }}>
            <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Body</p>
            <p className="text-sm text-slate-600 leading-relaxed whitespace-pre-line">{first.body}</p>
          </div>
        )}
      </div>

      {rest.length > 0 && (
        isPro ? (
          rest.map((tmpl, i) => (
            <div key={i} className="result-card p-6">
              <div className="flex items-start justify-between mb-4 gap-3">
                <div>
                  <p className="text-xs font-bold uppercase tracking-widest mb-1" style={{ color: '#059669' }}>Template {i + 2} of {templates.length}</p>
                  <h4 className="font-black text-slate-900 text-sm">{tmpl.title}</h4>
                </div>
                <CopyBtn text={`Subject: ${tmpl.subject}\n\n${tmpl.body}`} />
              </div>
              {tmpl.subject && (
                <div className="mb-3 p-3 rounded-xl" style={{ background: '#f0fdf4', border: '1px solid #d1fae5' }}>
                  <p className="text-xs font-bold uppercase tracking-wider mb-0.5" style={{ color: '#059669' }}>Subject</p>
                  <p className="text-sm font-semibold text-slate-800">{tmpl.subject}</p>
                </div>
              )}
              {tmpl.body && (
                <div className="p-3 rounded-xl" style={{ background: '#f8fafc', border: '1px solid #e2e8f0' }}>
                  <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Body</p>
                  <p className="text-sm text-slate-600 leading-relaxed whitespace-pre-line">{tmpl.body}</p>
                </div>
              )}
            </div>
          ))
        ) : (
          <ProGate feature={`Email Templates 2–${templates.length}`} onShowWaitlist={onShowWaitlist}>
            <div className="space-y-4">
              {rest.map((tmpl, i) => (
                <div key={i} className="result-card p-6">
                  <p className="text-xs font-bold uppercase tracking-widest mb-1" style={{ color: '#059669' }}>Template {i + 2}</p>
                  <h4 className="font-black text-slate-900 mb-3 text-sm">{tmpl.title}</h4>
                  {tmpl.subject && <div className="mb-2 p-3 rounded-xl" style={{ background: '#f0fdf4' }}><p className="text-sm font-semibold text-slate-800">{tmpl.subject}</p></div>}
                  {tmpl.body    && <div className="p-3 rounded-xl" style={{ background: '#f8fafc' }}><p className="text-sm text-slate-600 leading-relaxed">{tmpl.body.slice(0, 60)}…</p></div>}
                </div>
              ))}
            </div>
          </ProGate>
        )
      )}

      <ToolCard name="Mailchimp" description="Build, send, and automate email campaigns that convert readers into customers." url="https://mailchimp.com" icon={<Mail className="w-5 h-5 text-emerald-600" />} />
    </div>
  );
}

// ── Ad Copy Section ────────────────────────────────────────────────────────

function AdSection({ content }) {
  const { googleHeadlines, googleDescriptions, fbHeadline, fbBody, fbCTA } = parseAdCopy(content);

  return (
    <div className="space-y-5">
      <div className="result-card p-6">
        <div className="flex items-center gap-2 mb-4">
          <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: '#EFF6FF' }}>
            <Search className="w-4 h-4 text-blue-600" />
          </div>
          <h4 className="font-black text-slate-900 text-sm">Google Search Ad</h4>
          <span className="ml-auto text-xs font-semibold px-2.5 py-1 rounded-full" style={{ background: '#EFF6FF', color: '#1d4ed8' }}>Preview</span>
        </div>
        <div className="rounded-xl p-5" style={{ background: '#f8fafc', border: '1px solid #e2e8f0' }}>
          <div className="flex items-center gap-2 mb-2">
            <span className="text-[10px] px-1.5 py-0.5 rounded border font-medium text-slate-500" style={{ borderColor: '#cbd5e1' }}>Ad</span>
            <span className="text-xs text-slate-400">yourbusiness.com</span>
          </div>
          <p className="font-medium text-base mb-1.5 leading-snug" style={{ color: '#1a0dab' }}>
            {googleHeadlines.slice(0, 3).join(' · ') || 'Your Business · Professional Services · Contact Us Today'}
          </p>
          {googleDescriptions.map((d, i) => <p key={i} className="text-sm text-slate-500 leading-relaxed">{d}</p>)}
          {!googleDescriptions.length && <p className="text-sm text-slate-400">Your compelling ad description will appear here.</p>}
        </div>
        {googleHeadlines.length > 0 && (
          <div className="mt-4 pt-4 border-t border-slate-100">
            <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2.5">All Headlines</p>
            <div className="flex flex-wrap gap-1.5">
              {googleHeadlines.map((h, i) => (
                <span key={i} className="text-xs px-3 py-1.5 rounded-full font-semibold" style={{ background: '#EFF6FF', color: '#1d4ed8', border: '1px solid #BFDBFE' }}>{h}</span>
              ))}
            </div>
          </div>
        )}
        {googleDescriptions.length > 0 && (
          <div className="mt-3 pt-3 border-t border-slate-100">
            <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-2.5">Descriptions</p>
            <div className="space-y-2">
              {googleDescriptions.map((d, i) => (
                <div key={i} className="text-sm text-slate-600 px-3 py-2 rounded-lg" style={{ background: '#f8fafc', border: '1px solid #e2e8f0' }}>{d}</div>
              ))}
            </div>
          </div>
        )}
      </div>

      <div className="result-card p-6">
        <div className="flex items-center gap-2 mb-4">
          <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: '#EFF6FF' }}>
            <FacebookIcon />
          </div>
          <h4 className="font-black text-slate-900 text-sm">Facebook / Instagram Ad</h4>
          <span className="ml-auto text-xs font-semibold px-2.5 py-1 rounded-full" style={{ background: '#EFF6FF', color: '#1d4ed8' }}>Preview</span>
        </div>
        <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #e2e8f0' }}>
          <div className="px-4 py-3 flex items-center gap-3 bg-white" style={{ borderBottom: '1px solid #e2e8f0' }}>
            <div className="w-9 h-9 rounded-full flex items-center justify-center text-white text-sm font-black flex-shrink-0"
              style={{ background: 'linear-gradient(135deg,#059669,#047857)' }}>M</div>
            <div>
              <p className="font-bold text-slate-900 text-sm">Your Business</p>
              <p className="text-xs text-slate-400">Sponsored</p>
            </div>
            <div className="ml-auto text-slate-300 text-lg font-bold">···</div>
          </div>
          <div className="px-4 pt-3 pb-2 bg-white">
            <p className="text-sm text-slate-700 leading-relaxed">{fbBody || 'Your compelling Facebook ad body copy will appear here.'}</p>
          </div>
          <div className="mx-4 mb-3 rounded-xl h-28 flex items-center justify-center"
            style={{ background: 'linear-gradient(135deg,#ECFDF5,#D1FAE5)', border: '1.5px dashed #A7F3D0' }}>
            <div className="text-center">
              <div className="w-10 h-10 rounded-xl bg-emerald-100 flex items-center justify-center mx-auto mb-1.5">
                <TrendingUp className="w-5 h-5 text-emerald-600" />
              </div>
              <p className="text-emerald-600 text-xs font-semibold">Your Product / Service Image</p>
            </div>
          </div>
          <div className="px-4 py-3 flex items-center justify-between" style={{ background: '#f8fafc', borderTop: '1px solid #e2e8f0' }}>
            <div className="min-w-0 mr-3">
              <p className="text-[10px] text-slate-400 font-medium uppercase">yourbusiness.com</p>
              <p className="font-bold text-slate-900 text-sm truncate">{fbHeadline || 'Your Compelling Ad Headline'}</p>
            </div>
            <button className="flex-shrink-0 px-3.5 py-2 rounded-lg text-sm font-bold text-white" style={{ background: '#1877f2' }}>
              {fbCTA || 'Learn More'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// ── SEO Section ────────────────────────────────────────────────────────────

function SEOSection({ content }) {
  const { primary, secondary, longTail } = parseSEOKeywords(content);
  const [copied, setCopied] = useState(null);
  const groups = [
    { title: 'Primary Keywords',   items: primary,   bg: '#ECFDF5', bd: '#A7F3D0', text: '#065F46' },
    { title: 'Secondary Keywords', items: secondary, bg: '#EFF6FF', bd: '#BFDBFE', text: '#1e40af' },
    { title: 'Long-Tail Phrases',  items: longTail,  bg: '#FAF5FF', bd: '#E9D5FF', text: '#6d28d9' },
  ];
  const hasData = primary.length || secondary.length || longTail.length;
  if (!hasData) return <div>{renderContent(content)}</div>;

  const copyKeywords = (items, i) => {
    navigator.clipboard.writeText(items.join(', ')).catch(() => {});
    setCopied(i);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <div className="space-y-4">
      {groups.map((g, gi) => g.items.length > 0 && (
        <div key={gi} className="result-card p-6">
          <div className="flex items-center justify-between mb-3">
            <h4 className="font-black text-sm uppercase tracking-wide" style={{ color: g.text }}>{g.title}</h4>
            <button
              onClick={() => copyKeywords(g.items, gi)}
              className="text-xs px-2.5 py-1 rounded-lg font-semibold flex items-center gap-1.5 transition-all"
              style={{ background: copied === gi ? '#ECFDF5' : '#f1f5f9', color: copied === gi ? '#065F46' : '#64748b', border: copied === gi ? '1px solid #A7F3D0' : '1px solid #e2e8f0' }}>
              {copied === gi ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
              {copied === gi ? 'Copied!' : 'Copy all'}
            </button>
          </div>
          <div className="flex flex-wrap gap-2">
            {g.items.map((kw, i) => (
              <span key={i} className="inline-flex items-center px-3 py-1.5 rounded-full text-sm font-medium cursor-default transition-all hover:scale-105 hover:shadow-sm"
                style={{ background: g.bg, border: `1px solid ${g.bd}`, color: g.text }}>
                {kw}
              </span>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}

// ── Competitor Analysis Section ────────────────────────────────────────────

function CompetitorSection({ businessDescription, answers }) {
  const [competitorName, setCompetitorName] = useState('');
  const [analysis, setAnalysis]             = useState('');
  const [loading, setLoading]               = useState(false);
  const [error, setError]                   = useState('');

  const analyze = async () => {
    if (!competitorName.trim() || loading) return;
    setLoading(true);
    setError('');
    try {
      const res = await fetch('/api/competitor', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ businessDescription, answers, competitorName: competitorName.trim() }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || 'Failed');
      setAnalysis(data.analysis);
    } catch (err) {
      setError(err.message || 'Something went wrong. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="result-card p-6">
        <h4 className="font-black text-slate-900 text-sm mb-1">Analyze a Competitor</h4>
        <p className="text-slate-500 text-sm mb-4 leading-relaxed">
          Enter any competitor's name and get a specific positioning strategy against them — using your business context.
        </p>
        <div className="flex gap-2.5">
          <input
            value={competitorName}
            onChange={e => setCompetitorName(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && analyze()}
            placeholder="e.g., SweetCakes Bakery, Starbucks, Nike…"
            className="flex-1 px-4 py-2.5 rounded-xl text-sm text-slate-900 placeholder-slate-400 focus:outline-none transition-all"
            style={{ background: '#f8fafc', border: '1.5px solid #e2e8f0' }}
            onFocus={e => (e.target.style.borderColor = '#059669')}
            onBlur={e  => (e.target.style.borderColor = '#e2e8f0')}
          />
          <button onClick={analyze} disabled={!competitorName.trim() || loading}
            className="px-5 py-2.5 rounded-xl font-bold text-sm text-white transition-all disabled:opacity-40 flex items-center gap-2 flex-shrink-0"
            style={{ background: 'linear-gradient(135deg,#059669,#047857)', boxShadow: '0 3px 10px rgba(5,150,105,0.22)' }}>
            {loading ? (
              <><RefreshCw className="w-4 h-4 animate-spin" />Analyzing…</>
            ) : (
              <><Swords className="w-4 h-4" />Analyze</>
            )}
          </button>
        </div>
        {error && (
          <div className="mt-3 flex items-start gap-2 text-sm text-red-600 px-3 py-2 rounded-lg" style={{ background: '#FEF2F2', border: '1px solid #FECACA' }}>
            <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5" />
            {error}
          </div>
        )}
      </div>

      {analysis && (
        <div className="result-card p-6 sm:p-8">
          <div className="flex items-center gap-3 mb-5">
            <div className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0" style={{ background: '#fff7ed', border: '1px solid #fed7aa' }}>
              <Swords className="w-4 h-4 text-orange-500" />
            </div>
            <div className="flex-1 min-w-0">
              <h4 className="font-black text-slate-900 text-sm">vs. {competitorName}</h4>
              <p className="text-slate-400 text-xs">Competitive positioning analysis</p>
            </div>
            <CopyBtn text={analysis} />
          </div>
          {renderContent(analysis)}
        </div>
      )}

      {!analysis && !loading && (
        <div className="result-card p-10 text-center">
          <div className="w-12 h-12 rounded-xl flex items-center justify-center mx-auto mb-4" style={{ background: '#fff7ed', border: '1px solid #fed7aa' }}>
            <Swords className="w-6 h-6 text-orange-400" />
          </div>
          <p className="font-bold text-slate-700 mb-1">Ready to outsmart the competition</p>
          <p className="text-slate-400 text-sm max-w-sm mx-auto leading-relaxed">
            Enter any competitor above to get a specific strategy for winning their customers.
          </p>
        </div>
      )}
    </div>
  );
}

// ── Tool Card ──────────────────────────────────────────────────────────────

function ToolCard({ name, description, url, icon }) {
  return (
    <a href={url} target="_blank" rel="noopener noreferrer" style={{ textDecoration: 'none', display: 'block' }}>
      <div
        className="transition-all"
        style={{ background: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: 12, padding: '12px 14px', display: 'flex', alignItems: 'center', gap: 12, cursor: 'pointer', transition: 'box-shadow 0.16s, transform 0.16s' }}
        onMouseEnter={e => { e.currentTarget.style.boxShadow = '0 4px 14px rgba(16,185,129,0.12)'; e.currentTarget.style.transform = 'translateY(-1px)'; }}
        onMouseLeave={e => { e.currentTarget.style.boxShadow = 'none'; e.currentTarget.style.transform = 'translateY(0)'; }}>
        <div style={{ width: 38, height: 38, borderRadius: 9, flexShrink: 0, background: '#d1fae5', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          {icon}
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <span style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.07em', color: '#059669', display: 'block', marginBottom: 1 }}>Recommended Tool</span>
          <p style={{ margin: 0, fontWeight: 800, color: '#0f172a', fontSize: 13, lineHeight: 1.3 }}>{name}</p>
          <p style={{ margin: '2px 0 0', color: '#64748b', fontSize: 12, lineHeight: 1.45 }}>{description}</p>
        </div>
        <div style={{ flexShrink: 0, padding: '6px 13px', background: '#059669', color: '#fff', borderRadius: 8, fontSize: 12, fontWeight: 700 }}>Visit</div>
      </div>
    </a>
  );
}

const TOOL_RECOMMENDATIONS = {
  social: [
    { name: 'Canva',     description: 'Design eye-catching social media graphics in minutes.',          url: 'https://canva.com',    icon: <Share2 className="w-4 h-4 text-emerald-600" /> },
    { name: 'Hootsuite', description: 'Schedule and manage all your social posts from one dashboard.', url: 'https://hootsuite.com', icon: <CalendarDays className="w-4 h-4 text-emerald-600" /> },
  ],
  seo: [
    { name: 'Semrush',   description: 'Research keywords, track rankings, and outrank your competition.', url: 'https://semrush.com', icon: <Search className="w-4 h-4 text-emerald-600" /> },
  ],
};

function ToolRecommendations({ sectionKey }) {
  const tools = TOOL_RECOMMENDATIONS[sectionKey];
  if (!tools?.length) return null;
  return (
    <div style={{ marginTop: 16 }}>
      <p style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: '#94a3b8', marginBottom: 8 }}>Tools to help you execute</p>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {tools.map((tool, i) => <ToolCard key={i} {...tool} />)}
      </div>
    </div>
  );
}

// ── Regenerate Button ──────────────────────────────────────────────────────

function RegenerateBtn({ isPro, onRegenerate, loading, onShowWaitlist }) {
  const [showTip, setShowTip] = useState(false);
  const tipRef = useRef(null);

  useEffect(() => {
    if (!showTip) return;
    const handler = e => { if (tipRef.current && !tipRef.current.contains(e.target)) setShowTip(false); };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [showTip]);

  if (!isPro) {
    return (
      <div className="relative" ref={tipRef}>
        <button onClick={() => setShowTip(v => !v)}
          className="text-xs px-2.5 py-1.5 rounded-lg font-semibold flex items-center gap-1.5 transition-all"
          style={{ background: '#f1f5f9', color: '#94a3b8', border: '1px solid #e2e8f0', cursor: 'pointer' }}>
          <Lock className="w-3 h-3" />
          Regenerate
        </button>
        {showTip && (
          <div className="absolute right-0 top-full mt-2 z-50 w-56 rounded-xl p-4 bg-white"
            style={{ border: '1px solid #e2e8f0', boxShadow: '0 8px 28px rgba(0,0,0,0.1)' }}>
            <p className="text-sm font-bold text-slate-900 mb-1">Pro Feature</p>
            <p className="text-xs text-slate-500 mb-3 leading-relaxed">Regenerate any section with fresh AI-generated content tailored to your business.</p>
            <button
              onClick={() => { setShowTip(false); onShowWaitlist?.(); }}
              className="block w-full text-center text-xs font-bold py-2 rounded-lg text-white"
              style={{ background: 'linear-gradient(135deg,#059669,#047857)', border: 'none', cursor: 'pointer' }}>
              Join Waitlist
            </button>
          </div>
        )}
      </div>
    );
  }

  return (
    <button onClick={onRegenerate} disabled={loading}
      className="text-xs px-2.5 py-1.5 rounded-lg font-semibold flex items-center gap-1.5 transition-all disabled:opacity-50"
      style={{ background: '#ECFDF5', color: '#059669', border: '1px solid #A7F3D0' }}>
      <RefreshCw className={`w-3 h-3 ${loading ? 'animate-spin' : ''}`} />
      {loading ? 'Generating…' : 'Regenerate'}
    </button>
  );
}

// ── Copy Button ────────────────────────────────────────────────────────────

function CopyBtn({ text, label = '' }) {
  const [done, setDone] = useState(false);
  const copy = () => {
    navigator.clipboard.writeText(text).catch(() => {});
    setDone(true);
    setTimeout(() => setDone(false), 2000);
  };
  return (
    <button onClick={copy}
      className="text-xs px-2.5 py-1.5 rounded-lg font-semibold transition-all flex items-center gap-1.5 flex-shrink-0"
      style={{ background: done ? '#ECFDF5' : '#f1f5f9', color: done ? '#065F46' : '#64748b', border: done ? '1px solid #A7F3D0' : '1px solid #e2e8f0' }}>
      {done ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
      {done ? 'Copied!' : label || 'Copy'}
    </button>
  );
}

// ── Fade wrapper ───────────────────────────────────────────────────────────

function FadeIn({ children }) {
  return (
    <div className="animate-section-in">
      {children}
    </div>
  );
}

// ── Buy Me a Coffee card ───────────────────────────────────────────────────

function CoffeeCard({ onDismiss }) {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const t = setTimeout(() => setVisible(true), 3000);
    return () => clearTimeout(t);
  }, []);

  const dismiss = () => {
    setVisible(false);
    setTimeout(onDismiss, 380);
  };

  return (
    <div
      aria-label="Support MarketGenie"
      style={{
        position: 'fixed', bottom: 24, right: 24, zIndex: 90,
        width: 288,
        background: '#ffffff',
        border: '1px solid #e2e8f0',
        borderRadius: 16,
        boxShadow: '0 16px 48px rgba(0,0,0,0.12), 0 4px 16px rgba(5,150,105,0.1)',
        padding: '18px 18px 14px',
        transition: 'opacity 0.38s cubic-bezier(0.22,1,0.36,1), transform 0.38s cubic-bezier(0.22,1,0.36,1)',
        opacity: visible ? 1 : 0,
        transform: visible ? 'translateY(0) scale(1)' : 'translateY(16px) scale(0.97)',
        pointerEvents: visible ? 'auto' : 'none',
      }}
    >
      {/* Emerald top accent */}
      <div style={{
        position: 'absolute', top: 0, left: 16, right: 16, height: 2,
        background: 'linear-gradient(90deg, #059669, #34d399)',
        borderRadius: '0 0 99px 99px',
      }} />

      {/* X close */}
      <button
        onClick={dismiss}
        aria-label="Close"
        style={{
          position: 'absolute', top: 10, right: 10,
          background: 'none', border: 'none', cursor: 'pointer',
          color: '#cbd5e1', padding: 4, borderRadius: 6,
          display: 'flex', alignItems: 'center', lineHeight: 1,
          transition: 'color 0.15s ease',
        }}
        onMouseEnter={e => e.currentTarget.style.color = '#94a3b8'}
        onMouseLeave={e => e.currentTarget.style.color = '#cbd5e1'}
      >
        <X style={{ width: 14, height: 14 }} />
      </button>

      {/* Message */}
      <p style={{ fontSize: 13, lineHeight: 1.55, color: '#334155', marginBottom: 14, paddingRight: 20 }}>
        This strategy was built just for you — for free. If it helps your business, a coffee keeps the lights on ☕
      </p>

      {/* BMAC button */}
      <a
        href={BMAC_URL}
        target="_blank"
        rel="noopener noreferrer"
        style={{
          display: 'block', textAlign: 'center',
          padding: '9px 0',
          background: 'linear-gradient(135deg, #059669, #047857)',
          color: '#ffffff', fontWeight: 700, fontSize: 13,
          borderRadius: 10, textDecoration: 'none',
          boxShadow: '0 4px 14px rgba(5,150,105,0.3)',
          marginBottom: 10,
          transition: 'box-shadow 0.2s ease, transform 0.15s ease',
        }}
        onMouseEnter={e => { e.currentTarget.style.transform = 'translateY(-1px)'; e.currentTarget.style.boxShadow = '0 6px 20px rgba(5,150,105,0.4)'; }}
        onMouseLeave={e => { e.currentTarget.style.transform = 'translateY(0)'; e.currentTarget.style.boxShadow = '0 4px 14px rgba(5,150,105,0.3)'; }}
      >
        ☕ Buy Me a Coffee
      </a>

      {/* Maybe later */}
      <button
        onClick={dismiss}
        style={{
          display: 'block', width: '100%',
          background: 'none', border: 'none', cursor: 'pointer',
          color: '#94a3b8', fontSize: 12, textAlign: 'center', padding: '2px 0',
          transition: 'color 0.15s ease',
        }}
        onMouseEnter={e => e.currentTarget.style.color = '#64748b'}
        onMouseLeave={e => e.currentTarget.style.color = '#94a3b8'}
      >
        Maybe later
      </button>
    </div>
  );
}

// ── Main Component ─────────────────────────────────────────────────────────

export default function StrategyResults({ strategy, businessDescription, answers = [], onReset, isDemo = false, isSample = false, isStreaming = false, onShowWaitlist, onStartFree }) {

  const stratSections = useMemo(() => {
    const all = parseSections(strategy || '');
    if (isStreaming && all.length > 1 && all[all.length - 1].content === '') {
      return all.slice(0, -1);
    }
    return all;
  }, [strategy, isStreaming]);

  const allSections = useMemo(() => [
    ...stratSections,
    ...(isSample ? [] : [{ title: 'Competitor Analysis', content: '', synthetic: true }]),
  ], [stratSections, isSample]);

  const [activeIdx, setActiveIdx]             = useState(0);
  const [sectionOverrides, setSectionOverrides] = useState({});
  const [regenerating, setRegenerating]       = useState(null);
  const [winsProgress, setWinsProgress]       = useState({ checked: 0, total: 0 });
  const [showCoffee, setShowCoffee]           = useState(false);
  const [exporting,  setExporting]            = useState(false);
  const tabsRef     = useRef(null);
  const coffeeArmed = useRef(false);

  useEffect(() => {
    if (isStreaming || coffeeArmed.current || isDemo || isSample) return;
    try { if (localStorage.getItem(BMAC_DISMISSED_KEY)) return; } catch {}
    coffeeArmed.current = true;
    setShowCoffee(true);
  }, [isStreaming, isDemo, isSample]);

  const handleCoffeeDismiss = useCallback(() => {
    try { localStorage.setItem(BMAC_DISMISSED_KEY, '1'); } catch {}
    setShowCoffee(false);
  }, []);

  const handleExport = useCallback(async () => {
    if (exporting) return;
    setExporting(true);
    try {
      const sections = stratSections
        .map((sec, i) => ({
          title:   sec.title,
          content: sectionOverrides[i] ?? sec.content,
        }))
        .filter(sec => isDemo || !FULLY_LOCKED.has(getMeta(sec.title).key));

      if (isDemo && !isSample) {
        sections.push({
          title:   'Competitor Analysis',
          content: 'Your Competitor Analysis is generated live and interactive in the MarketGenie dashboard.\n\nOpen the Competitor Analysis tab in your results to run a custom analysis for any competitor you choose.\n\nThis section is available in full within the live app.',
        });
      }

      await exportToPDF(sections, businessDescription);
    } catch (err) {
      console.error('PDF export failed:', err);
    } finally {
      setExporting(false);
    }
  }, [exporting, stratSections, sectionOverrides, isDemo, isSample, businessDescription]);

  // Extract base score from the score section (for sidebar widget)
  const scoreContent = useMemo(() => {
    const sec = stratSections.find(s => getMeta(s.title).key === 'score');
    if (!sec) return '';
    const idx = stratSections.indexOf(sec);
    return sectionOverrides[idx] ?? sec.content;
  }, [stratSections, sectionOverrides]);

  const baseScore     = useMemo(() => scoreContent ? extractScore(scoreContent) : null, [scoreContent]);
  const scoreBonus    = winsProgress.total > 0 ? Math.round((winsProgress.checked / winsProgress.total) * 8) : 0;
  const adjustedScore = baseScore !== null ? Math.min(100, baseScore + scoreBonus) : null;
  const scoreLabel    = adjustedScore !== null
    ? (adjustedScore >= 80 ? 'Excellent' : adjustedScore >= 60 ? 'Good' : 'Needs Work')
    : null;

  const handleWinsChange = useCallback((checked, total) => {
    setWinsProgress({ checked, total });
  }, []);

  if (!strategy || stratSections.length === 0) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ background: '#f8fafc' }}>
        <p className="text-slate-400">No strategy data available.</p>
      </div>
    );
  }

  const active       = allSections[activeIdx];
  const activeMeta   = getMeta(active.title);
  const isScore      = activeMeta.key === 'score';
  const isAds        = activeMeta.key === 'ads';
  const isSEO        = activeMeta.key === 'seo';
  const isSocial     = activeMeta.key === 'social';
  const isEmail      = activeMeta.key === 'email';
  const isCompetitor = activeMeta.key === 'competitor';
  const isSynthetic  = !!active.synthetic;

  const activeContent    = sectionOverrides[activeIdx] ?? active.content;
  const isFullyLocked    = !isDemo && FULLY_LOCKED.has(activeMeta.key);
  const isPartialLock    = !isDemo && (isEmail || isScore);

  const handleRegenerate = async () => {
    if (!isDemo || isSynthetic || isSample) return;
    setRegenerating(activeIdx);
    try {
      const res = await fetch('/api/regenerate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ businessDescription, answers, sectionKey: activeMeta.key }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setSectionOverrides(prev => ({ ...prev, [activeIdx]: data.content }));
    } catch (err) {
      console.error('Regenerate failed:', err.message);
    } finally {
      setRegenerating(null);
    }
  };

  const scrollTabIntoView = (i) => {
    const bar = tabsRef.current;
    if (!bar) return;
    const btn = bar.children[i];
    if (btn) btn.scrollIntoView({ behavior: 'smooth', inline: 'center', block: 'nearest' });
  };

  const handleTab = (i) => {
    setActiveIdx(i);
    scrollTabIntoView(i);
  };

  return (
    <div className="flex flex-col overflow-hidden" style={{ height: '100vh', background: '#f8fafc' }}>

      {/* ── Top header bar ─────────────────────────────────────────── */}
      <header className="flex-shrink-0 flex items-center justify-between px-5 py-3"
        style={{ background: '#ffffff', borderBottom: '1px solid #e2e8f0', zIndex: 50 }}>

        <div className="flex items-center gap-2.5">
          <div className="w-7 h-7 rounded-lg flex items-center justify-center text-white flex-shrink-0"
            style={{ background: 'linear-gradient(135deg,#059669,#047857)' }}>
            <Zap className="w-3.5 h-3.5" />
          </div>
          <span className="font-black text-sm text-slate-900">MarketGenie</span>
        </div>

        <div className="flex items-center gap-2.5">
          {isStreaming ? (
            <div className="hidden sm:flex items-center gap-1.5 rounded-full px-3 py-1"
              style={{ background: '#FEF3C7', border: '1px solid #FDE68A' }}>
              <span className="w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse" />
              <span className="text-amber-700 text-xs font-bold">Generating…</span>
            </div>
          ) : (
            <div className="hidden sm:flex items-center gap-1.5 rounded-full px-3 py-1"
              style={{ background: '#ECFDF5', border: '1px solid #A7F3D0' }}>
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
              <span className="text-emerald-700 text-xs font-bold">Strategy Ready</span>
            </div>
          )}
          {!isStreaming && (
            <button
              onClick={handleExport}
              disabled={exporting}
              className="hidden sm:flex items-center gap-1.5 text-xs font-semibold px-3.5 py-2 rounded-lg transition-all"
              style={exporting
                ? { background: '#ECFDF5', color: '#059669', border: '1px solid #A7F3D0' }
                : { background: 'linear-gradient(135deg,#059669,#047857)', color: '#ffffff', boxShadow: '0 2px 8px rgba(5,150,105,0.28)' }}
            >
              {exporting
                ? <><Loader2 className="w-3.5 h-3.5 animate-spin" />Exporting…</>
                : <><Download className="w-3.5 h-3.5" />Export PDF</>}
            </button>
          )}
          <button onClick={onReset}
            className="text-xs font-semibold px-3.5 py-2 rounded-lg border transition-all hover:bg-slate-50"
            style={{ color: '#475569', borderColor: '#e2e8f0' }}>
            New Strategy
          </button>
        </div>
      </header>

      {/* ── Sample / Demo banners ──────────────────────────────────── */}
      {isSample && (
        <div className="flex-shrink-0 flex items-center justify-center gap-2 py-2 px-4 text-center text-xs"
          style={{ background: 'linear-gradient(90deg,#1e40af,#1d4ed8)', borderBottom: '1px solid #3b82f6' }}>
          <span style={{ color: '#bfdbfe', fontWeight: 600 }}>
            Sample Strategy — The Corner Bistro, Chicago
          </span>
          <span style={{ color: '#93c5fd' }}>·</span>
          <button onClick={onStartFree} style={{ color: '#ffffff', fontWeight: 800, background: 'none', border: 'none', cursor: 'pointer', textDecoration: 'underline', padding: 0, fontSize: 12 }}>
            Generate yours free
          </button>
        </div>
      )}

      {isDemo && !isSample && (
        <div className="flex-shrink-0 flex items-center justify-center py-2 px-4"
          style={{ background: 'linear-gradient(90deg,#065F46,#047857)', borderBottom: '1px solid #059669' }}>
          <span style={{ color: '#a7f3d0', fontSize: 12, fontWeight: 600 }}>
            Demo Mode — Full Pro access · All sections unlocked · Regenerate enabled
          </span>
        </div>
      )}

      {/* ── Split area ─────────────────────────────────────────────── */}
      <div className="flex flex-1 overflow-hidden">

        {/* ── Sidebar (desktop only) ───────────────────────────────── */}
        <aside className="hidden lg:flex flex-col flex-shrink-0 overflow-y-auto"
          style={{ width: 268, background: '#ffffff', borderRight: '1px solid #e2e8f0' }}>

          {/* Business description */}
          <div className="p-5" style={{ borderBottom: '1px solid #f1f5f9' }}>
            <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400 mb-1.5">Strategy for</p>
            <p className="text-xs text-slate-600 leading-relaxed font-medium" style={{
              display: '-webkit-box',
              WebkitLineClamp: 3,
              WebkitBoxOrient: 'vertical',
              overflow: 'hidden',
            }}>
              {businessDescription}
            </p>
          </div>

          {/* Section navigation */}
          <nav className="flex-1 p-3">
            <p className="text-[10px] font-bold uppercase tracking-widest text-slate-400 px-3 mb-2">Sections</p>
            <div className="space-y-0.5">
              {allSections.map((sec, i) => {
                const m      = getMeta(sec.title);
                const active = i === activeIdx;
                const locked = !isDemo && FULLY_LOCKED.has(m.key);
                const partial = !isDemo && (m.key === 'email' || m.key === 'score');
                return (
                  <button key={i} onClick={() => handleTab(i)}
                    className={`sidebar-item ${active ? 'active' : ''}`}>
                    <m.Icon
                      className="flex-shrink-0"
                      style={{
                        width: 15, height: 15,
                        color: active ? m.color : '#94a3b8',
                        transition: 'color 0.15s ease',
                      }}
                    />
                    <span className="flex-1 truncate text-xs">{sec.title}</span>
                    {locked && <Lock style={{ width: 11, height: 11, color: '#cbd5e1', flexShrink: 0 }} />}
                    {partial && !active && <Lock style={{ width: 10, height: 10, color: '#e2e8f0', flexShrink: 0 }} />}
                    {isStreaming && i === stratSections.length - 1 && (
                      <span className="w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse flex-shrink-0" />
                    )}
                  </button>
                );
              })}
            </div>
          </nav>

          {/* Score widget */}
          {adjustedScore !== null && (
            <div className="p-4" style={{ borderTop: '1px solid #f1f5f9' }}>
              <div className="rounded-xl p-4" style={{ background: '#f8fafc', border: '1px solid #e2e8f0' }}>
                <div className="flex items-center justify-between mb-3">
                  <p className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Marketing Score</p>
                  {winsProgress.checked > 0 && (
                    <span className="text-[9px] font-bold px-1.5 py-0.5 rounded-full" style={{ background: '#ECFDF5', color: '#065F46' }}>
                      +{scoreBonus} from wins
                    </span>
                  )}
                </div>
                <div className="flex items-center gap-3">
                  <MiniScoreRing score={adjustedScore} />
                  <div>
                    <p className="text-3xl font-black text-slate-900 leading-none">{adjustedScore}</p>
                    <p className="text-xs text-slate-400 mt-0.5">/100 · {scoreLabel}</p>
                  </div>
                </div>
                {winsProgress.total > 0 && (
                  <div className="mt-3 pt-3" style={{ borderTop: '1px solid #e2e8f0' }}>
                    <div className="flex justify-between text-[10px] text-slate-400 mb-1">
                      <span>Quick Wins Progress</span>
                      <span className="font-bold">{winsProgress.checked}/{winsProgress.total}</span>
                    </div>
                    <div className="h-1.5 rounded-full bg-slate-200 overflow-hidden">
                      <div className="h-full rounded-full bg-emerald-500 transition-all duration-500 ease-out"
                        style={{ width: `${winsProgress.total > 0 ? (winsProgress.checked / winsProgress.total) * 100 : 0}%` }} />
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}
        </aside>

        {/* ── Main content area ─────────────────────────────────────── */}
        <main className="flex-1 overflow-y-auto flex flex-col" style={{ background: '#f8fafc' }}>

          {/* Mobile tab bar */}
          <div className="lg:hidden sticky top-0 z-40 flex-shrink-0"
            style={{ background: '#ffffff', borderBottom: '1px solid #e2e8f0' }}>
            <div ref={tabsRef} className="flex gap-1.5 px-4 py-3 overflow-x-auto"
              style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
              {isStreaming && (
                <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold flex-shrink-0"
                  style={{ background: '#FEF3C7', color: '#92400E', border: '1px solid #FDE68A' }}>
                  <span className="w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse" />
                  {stratSections.length}/7
                </div>
              )}
              {allSections.map((sec, i) => {
                const m      = getMeta(sec.title);
                const isAct  = i === activeIdx;
                const locked = !isDemo && FULLY_LOCKED.has(m.key);
                return (
                  <button key={i} onClick={() => handleTab(i)}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-bold whitespace-nowrap flex-shrink-0 transition-all"
                    style={{
                      background: isAct ? '#059669' : '#f1f5f9',
                      color: isAct ? '#fff' : locked ? '#94a3b8' : '#64748b',
                      boxShadow: isAct ? '0 2px 8px rgba(5,150,105,0.22)' : 'none',
                    }}>
                    <m.Icon style={{ width: 12, height: 12 }} />
                    {m.short}
                    {locked && <Lock style={{ width: 10, height: 10, opacity: 0.6 }} />}
                  </button>
                );
              })}
            </div>
          </div>

          {/* Content */}
          <div className="flex-1 px-5 sm:px-8 pt-7 pb-10">
            <div className="max-w-3xl mx-auto">

              <FadeIn key={activeIdx}>

                {/* Section header */}
                <div className="flex items-start justify-between mb-5 gap-4">
                  <div className="flex items-center gap-3 min-w-0">
                    <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0"
                      style={{ background: activeMeta.color + '12', border: `1px solid ${activeMeta.color}22` }}>
                      <activeMeta.Icon style={{ width: 18, height: 18, color: activeMeta.color }} />
                    </div>
                    <div className="min-w-0">
                      <h2 className="text-lg font-black text-slate-900 leading-tight truncate">{active.title}</h2>
                      <p className="text-slate-400 text-xs mt-0.5">{activeIdx + 1} of {allSections.length} sections</p>
                    </div>
                  </div>
                  {!isSynthetic && (
                    <div className="flex items-center gap-1.5 flex-shrink-0">
                      <CopyBtn text={`${active.title}\n\n${activeContent}`} />
                      <RegenerateBtn
                        isPro={isDemo && !isSample}
                        onRegenerate={handleRegenerate}
                        loading={regenerating === activeIdx}
                        onShowWaitlist={onShowWaitlist}
                      />
                    </div>
                  )}
                </div>

                {/* ── Section-specific rendering ── */}

                {isScore && (
                  <ScoreSection
                    content={activeContent}
                    isPro={isDemo}
                    onShowWaitlist={onShowWaitlist}
                    adjustedScore={adjustedScore}
                    onCheckedChange={handleWinsChange}
                  />
                )}

                {isAds && (
                  isDemo
                    ? <AdSection content={activeContent} />
                    : <ProGate feature="Ad Copy" onShowWaitlist={onShowWaitlist}>
                        <AdSection content={activeContent} />
                      </ProGate>
                )}

                {isSEO && (
                  isDemo ? (
                    <>
                      <SEOSection content={activeContent} />
                      <ToolRecommendations sectionKey="seo" />
                    </>
                  ) : (
                    <ProGate feature="SEO Keywords" onShowWaitlist={onShowWaitlist}>
                      <SEOSection content={activeContent} />
                    </ProGate>
                  )
                )}

                {isEmail && (
                  <EmailSection content={activeContent} isPro={isDemo} onShowWaitlist={onShowWaitlist} />
                )}

                {isCompetitor && (
                  isSample ? (
                    <div className="result-card p-6 sm:p-8">
                      <div className="flex items-center gap-3 mb-5">
                        <div className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0" style={{ background: '#fff7ed', border: '1px solid #fed7aa' }}>
                          <Swords className="w-4 h-4 text-orange-500" />
                        </div>
                        <div>
                          <h4 className="font-black text-slate-900 text-sm">vs. Maple Street Grill</h4>
                          <p className="text-slate-400 text-xs">Competitive positioning analysis · Lincoln Park, Chicago</p>
                        </div>
                      </div>
                      {renderContent(activeContent)}
                    </div>
                  ) : isDemo ? (
                    <CompetitorSection businessDescription={businessDescription} answers={answers} />
                  ) : (
                    <ProGate feature="Competitor Analysis" onShowWaitlist={onShowWaitlist}>
                      <div className="space-y-4">
                        <div className="result-card p-6">
                          <div className="h-4 rounded-lg bg-slate-200 w-44 mb-3" />
                          <div className="flex gap-3">
                            <div className="flex-1 h-10 rounded-xl bg-slate-100" />
                            <div className="w-24 h-10 rounded-xl bg-emerald-200" />
                          </div>
                        </div>
                        <div className="result-card p-6">
                          <div className="h-3.5 rounded bg-slate-200 w-56 mb-4" />
                          <div className="space-y-2">
                            {[80,65,90,55].map((w, i) => <div key={i} className="h-2.5 rounded bg-slate-100" style={{ width: `${w}%` }} />)}
                          </div>
                        </div>
                      </div>
                    </ProGate>
                  )
                )}

                {/* Generic sections: target, social, calendar */}
                {!isScore && !isAds && !isSEO && !isEmail && !isCompetitor && (
                  <div className="result-card p-6 sm:p-8">
                    {renderContent(activeContent)}
                    {isStreaming && activeIdx === allSections.length - 2 && (
                      <span className="inline-block w-2 h-4 ml-0.5 align-middle rounded-sm bg-emerald-400 animate-pulse" />
                    )}
                    {isSocial && <ToolRecommendations sectionKey="social" />}
                  </div>
                )}

                {/* ── Section navigation ── */}
                <div className="flex items-center justify-between mt-8 pt-6" style={{ borderTop: '1px solid #e2e8f0' }}>
                  <button onClick={() => handleTab(Math.max(0, activeIdx - 1))} disabled={activeIdx === 0}
                    className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold transition-all disabled:opacity-30 disabled:cursor-not-allowed hover:bg-slate-100"
                    style={{ color: '#64748b' }}>
                    <ChevronLeft className="w-4 h-4" />
                    Previous
                  </button>
                  <span className="text-xs text-slate-300 font-medium">{activeIdx + 1} / {allSections.length}</span>
                  <button onClick={() => handleTab(Math.min(allSections.length - 1, activeIdx + 1))}
                    disabled={activeIdx === allSections.length - 1}
                    className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-semibold transition-all disabled:opacity-30 disabled:cursor-not-allowed hover:bg-emerald-50"
                    style={{ color: activeIdx === allSections.length - 1 ? '#94a3b8' : '#059669' }}>
                    Next
                    <ChevronRight className="w-4 h-4" />
                  </button>
                </div>

              </FadeIn>
            </div>
          </div>

          {/* Bottom bar */}
          <div className="flex-shrink-0 px-6 py-4" style={{ background: '#ffffff', borderTop: '1px solid #e2e8f0' }}>
            <div className="max-w-3xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-2">
              <p className="text-slate-400 text-xs">© 2026 MarketGenie · Powered by Claude AI</p>
              <button onClick={onReset} className="emerald-btn px-5 py-2 rounded-xl text-xs font-bold">
                <span>Generate New Strategy</span>
              </button>
            </div>
          </div>

        </main>
      </div>

      {showCoffee && <CoffeeCard onDismiss={handleCoffeeDismiss} />}
    </div>
  );
}
